### ISSUE TITLE
todo in next iteration

### ISSUE THREAD

**Issue by e-hein** [e-hein/professional-tour-of-heroes#11]
- [ ]  earlier windows compatibility
- [ ]  libs/core/README.md code scaffolding project name
- [ ]  https://github.com/e-hein/professional-tour-of-heroes/commit/5e7e9eb83f482bf891c8304fefd1b9fa6dae18a2 fix Readmes
- [ ]  https://github.com/e-hein/professional-tour-of-heroes/pull/10/commits/339766f208e47eefcd5a507d39b1715d4f5b72c4 (demo-app) minor fixes
